version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: husky
    versions:
    - 6.0.0
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: gatsby
    versions:
    - 2.32.6
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
